# Generated by Django 3.0.5 on 2020-05-21 03:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_famousquotes'),
    ]

    operations = [
        migrations.CreateModel(
            name='UncategorizedBlog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Uncategorized Blog Title')),
                ('content', models.TextField(verbose_name='Uncategorized Blog Content')),
            ],
            options={
                'verbose_name_plural': 'Uncategorized Blog Posts',
            },
        ),
        migrations.CreateModel(
            name='UnclassifiedBlogImages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blog_image', models.ImageField(upload_to='unclassified_blog_images')),
                ('image_description', models.TextField()),
                ('related_blog', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.UncategorizedBlog')),
            ],
            options={
                'verbose_name_plural': 'Uncategorized Blog Posts Images',
            },
        ),
    ]
