# Generated by Django 3.0.5 on 2020-05-21 18:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_blogcategory_category_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogcategory',
            name='number_of_blogs',
        ),
    ]
