TECHNOLOGY_CHOICES = [
    ('Python', 'Python'),
    ('Javascript', 'Javascript'),
    ('React JS', 'React JS'),
    ('Vue JS', 'Vue JS'),
    ('Angular', 'Angular'),
    ('HTML', 'HTML'),
    ('CSS', 'CSS'),
    ('Bootstrap', 'Bootstrap'),
    ('Materialize', 'Materialize'),
    ('Bulma', 'Bulma'),
    ('Node', 'Node'),
    ('Jquery', 'Jquery'),
    ('Express', 'Express'),
    ('Nuxt JS', 'Nuxt JS'),
    ('PHP', 'PHP'),
    ('Laravel', 'Laravel'),
    ('Mongo DB', 'Mongo DB'),
    ('MySQL', 'MySQL'),
]